export const UPDATE_ELEMENT = 'ROCKSTARS/USERACTIONS/UPDATE_ELEMENT';

//Dashboard Activities
export const REQUIRE_DASHBOARDACTIVITIES = 'ROCKSTARS/DASHBOARD/REQUIRE_DASHBOARDACTIVITIES';
export const RECEIVE_DASHBOARDACTIVITIES = 'ROCKSTARS/DASHBOARD/RECEIVE_DASHBOARDACTIVITIES';
export const RECEIVE_DASHBOARDACTIVITY_ERROR = 'ROCKSTARS/DASHBOARD/RECEIVE_DASHBOARDACTIVITY_ERROR';

//Activities
export const REQUIRE_ACTIVITIES = 'ROCKSTARS/ACTIVITY/REQUIRE_ACTIVITIES';
export const RECEIVE_ACTIVITIES = 'ROCKSTARS/ACTIVITY/RECEIVE_ACTIVITIES';
export const RECEIVE_ACTIVITY_ERROR = 'ROCKSTARS/ACTIVITY/RECEIVE_ACTIVITY_ERROR';
export const ADD_ACTIVITY = 'ROCKSTARS/ACTIVITY/ADD_ACTIVITY';

//Categories
export const REQUIRE_CATEGORIES = 'ROCKSTARS/CATEGORY/REQUIRE_CATEGORIES';
export const RECEIVE_CATEGORIES = 'ROCKSTARS/CATEGORY/RECEIVE_CATEGORIES';
export const RECEIVE_CATEGORY_ERROR = 'ROCKSTARS/CATEGORY/RECEIVE_CATEGORY_ERROR';
export const ADD_CATEGORY = 'ROCKSTARS/CATEGORY/ADD_CATEGORY';
export const REMOVE_CATEGORY = 'ROCKSTARS/CATEGORY/REMOVE_CATEGORY';

//Chapters
export const REQUIRE_CHAPTERS = 'ROCKSTARS/CHAPTER/REQUIRE_CHAPTERS';
export const RECEIVE_CHAPTERS = 'ROCKSTARS/CHAPTER/RECEIVE_CHAPTERS';
export const RECEIVE_CHAPTER_ERROR = 'ROCKSTARS/CHAPTER/RECEIVE_CHAPTER_ERROR';
export const ADD_CHAPTER = 'ROCKSTARS/CHAPTER/ADD_CHAPTER';
export const REMOVE_CHAPTER = 'ROCKSTARS/CHAPTER/REMOVE_CHAPTER';

//Users
export const REQUIRE_USERS = 'ROCKSTARS/USER/REQUIRE_USERS';
export const RECEIVE_USERS = 'ROCKSTARS/USER/RECEIVE_USERS';
export const RECEIVE_USER_ERROR = 'ROCKSTARS/USER/RECEIVE_USER_ERROR';
export const ADD_USER = 'ROCKSTARS/USER/ADD_USER';
export const REMOVE_USER = 'ROCKSTARS/USER/REMOVE_USER';

//Auth
export const UN_AUTHORIZED = 'ROCKSTARS/AUTH/UN_AUTHORIZED';
export const DO_LOGIN = 'ROCKSTARS/AUTH/DO_LOGIN';
export const DO_LOGOUT = 'ROCKSTARS/AUTH/DO_LOGOUT';
export const LOGGED_OUT = 'ROCKSTARS/AUTH/LOGGED_OUT';
export const RECEIVE_LOGIN_ERROR = 'ROCKSTARS/AUTH/RECEIVE_LOGIN_ERROR';
export const CLEAR_LOGIN_ERROR = 'ROCKSTARS/AUTH/CLEARLOGIN_ERROR';
export const RECEIVE_TOKEN = 'ROCKSTARS/AUTH/RECEIVE_TOKEN';
