export const UPDATE_ELEMENT = 'ROCKSTARS/USERACTIONS/UPDATE_ELEMENT';

//Activities
export const REQUIRE_ACTIVITIES = 'ROCKSTARS/ACTIVITY/REQUIRE_ACTIVITIES';
export const RECEIVE_ACTIVITIES = 'ROCKSTARS/ACTIVITY/RECEIVE_ACTIVITIES';
export const RECEIVE_ACTIVITY_ERROR = 'ROCKSTARS/ACTIVITY/RECEIVE_ACTIVITY_ERROR';

export const UN_AUTHORIZED = 'ROCKSTARS/GENERAL/UN_AUTHORIZED';
export const DO_LOGIN = 'ROCKSTARS/GENERAL/DO_LOGIN';
